<div id="fortis-data" data-config='<?= json_encode($block->getJSConfig()) ?>'></div>
<?php
if ($block->getData('error_html')): ?>
    <div class="error-container">
        <?= $block->getData('error_html'); ?>
    </div>
    <?php
endif; ?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'src' => $block->getViewFileUrl('Fortispay_Fortis::js/view/payment/fortis-iframe.js'),
        'nonce' => $block->getNonce()
    ],
    '',
    false
); ?>

