<?php
/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div id="fortis-data" data-config='<?=$escaper->escapeHtmlAttr(json_encode($block->getJSConfig()))?>'></div>
<?php
if ($block->getData('error_message')): ?>
    <div class="error-container">
        <div class="error-message error"><?= $escaper->escapeHtml($block->getData('error_message')) ?></div>
    </div>
    <?php
endif; ?>
