<?php
// @codingStandardsIgnoreFile

/** @var Fortispay\Fortis\Block\Customer\VaultAccountRenderer $block */

$accNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td data-th="<?= $block->escapeHtml(__('Account Number')) ?>" class="col card-number">
        <span><?= $block->escapeHtml(__('ending')) ?></span> <?= /* @noEscape */ $accNumberView ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('ACH Account')) ?>" class="col ach-account card-type">
        <img src="<?= $block->escapeHtmlAttr($block->getIconUrl()) ?>"
             width="<?= $block->escapeHtmlAttr($block->getIconWidth()) ?>"
             height="<?= $block->escapeHtmlAttr($block->getIconHeight()) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Fortis Logo')) ?>">
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
        <form class="form"
              action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input name="public_hash"
                   value="<?= $block->escapeHtmlAttr($block->getToken()->getPublicHash()) ?>"
                   type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtmlAttr(__('Delete')) ?>",
                            "content": "Are you sure you want to delete this Fortis ACH account?"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>

